spring.application.name=url-shortener
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.baseline-on-migrate=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.base-url=http://localhost:8080
app.frontend-url=http://localhost:5174

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

jwt.secret=MyVeryLongSecretKeyForUrlShortenerApplication123456789
jwt.expiration=900000

security.jwt.refresh-token-expiration-days=7

ipinfo.token=13df8dbd608510

app.rate-limit.shorten-url=5
app.rate-limit.login=10
app.rate-limit.register=3

app.url.default-expiry-days=7
app.url.max-expiry-days=10
app.url.grace-period-days=30
app.url.default-extend-days=5
app.redirect.abuse-threshold=1000
app.redirect.block-duration=10
app.url.max-active-urls=20

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=viratky11@gmail.com
spring.mail.password=yaat lavp gjmn egqd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true